### PR TITLE
OOP school library: preserve dataPreserve data

### PR DESCRIPTION
**Pull request by VaneCode**
-Created class HandleFiles to manage the files books.json, people.json, and rentals.json.
-Added method read_books, write_books, read_people, write_people, read_rentals, and write_rentals in HandleFiles.
-Added class HandleFiles in the class App to read data from the files, and also to write the data on them.

### CODE REVIEW

**Review by Bondok6 — COMMENTED** [review]
## Hi @VaneCode 🙋‍♂️ , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has been done individually and this is a pair programming project. Everyone on your team should make a commit in this PR.

image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by VaneCode** [comment]
Hello @Bondok6, yesterday my partner did not feel that he had enough knowledge to assume the role of driver, so he assumed the role of navigator and that is the reason why there are no commits for him. Could you please clarify what we should do now?

**Comment by Bondok6** [comment]
Hi @VaneCode, you can ask your partner to make at least one commit (ie a small change), then submit the same PR again and another reviewer will review your project.

**Comment by VaneCode** [comment]
Hello @Bondok6, thanks for your help.

**Review by mukhammadrizooff — APPROVED** [review]
Hi @TEAM, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
